---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

# ignore:
# vendor'd code (that has vendor in its path)
# protoc generated golang (*.pb.go)
# protoc/include contains well-known-types proto definitions that are not imported by toolshare
exclude: (vendor|\.pb\.go|proto/include|\.deepcopy\.go)

repos:
  - repo: git://github.com/dnephin/pre-commit-golang
    rev: master
    hooks:
      - id: go-fmt
      - id: go-imports
      - id: golangci-lint
      - id: go-unit-tests
      - id: go-build
      - id: go-mod-tidy

  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.0.12
    hooks:
      - id: yamlfmt
        args:
          - --mapping=2
          - --sequence=4
          - --offset=2
          - --width=1200    # match .yamllint.yaml; we don't care about line-length.
        exclude: .+/helm/templates/.+

  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.12
    hooks:
      - id: helmlint

  - repo: https://github.com/codingjoe/relint
    rev: 1.2.1
    hooks:
      - id: relint

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-added-large-files
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: forbid-new-submodules
      - id: mixed-line-ending
      - id: pretty-format-json
        args:
          - --autofix
      - id: trailing-whitespace
