---
# permissions for end users to view managedclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: managedcluster-viewer-role
rules:
  - apiGroups:
      - compute.tencentcloud.kubecooler.com
    resources:
      - managedclusters
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - compute.tencentcloud.kubecooler.com
    resources:
      - managedclusters/status
    verbs:
      - get
