---
# permissions for end users to edit managedclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: managedcluster-editor-role
rules:
  - apiGroups:
      - compute.tencentcloud.kubecooler.com
    resources:
      - managedclusters
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - compute.tencentcloud.kubecooler.com
    resources:
      - managedclusters/status
    verbs:
      - get
