# permissions for end users to edit subnets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: subnet-editor-role
rules:
- apiGroups:
  - network.tencentcloud.kubecooler.com
  resources:
  - subnets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.tencentcloud.kubecooler.com
  resources:
  - subnets/status
  verbs:
  - get
