/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1alpha1

import (
	v20170312 "github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/vpc/v20170312"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// EDIT THIS FILE!  THIS IS SCAFFOLDING FOR YOU TO OWN!
// NOTE: json tags are required.  Any new fields you add must have json tags for the fields to be serialized.

// SecurityGroupSpec defines the desired state of SecurityGroup
type SecurityGroupSpec struct {
	// INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
	// Important: Run "make" to regenerate code after modifying this file

	// Foo is an example field of SecurityGroup. Edit SecurityGroup_types.go to remove/update
	Region                 *string                           `json:"region,omitempty"`
	SecurityGroup          *v20170312.SecurityGroup          `json:"securityGroup,omitempty"`
	SecurityGroupPolicySet *v20170312.SecurityGroupPolicySet `json:"securityGroupPolicySet,omitempty"`
}

// SecurityGroupStatus defines the observed state of SecurityGroup
type SecurityGroupStatus struct {
	// INSERT ADDITIONAL STATUS FIELD - define observed state of cluster
	// Important: Run "make" to regenerate code after modifying this file
	Status                       *string                           `json:"status,omitempty"`
	Reason                       *string                           `json:"reason,omitempty"`
	Code                         *string                           `json:"code,omitempty"`
	LastRetry                    *string                           `json:"lastRetry,omitempty"`
	RetryCount                   *int                              `json:"retryCount,omitempty"`
	SecurityGroupStatus          *v20170312.SecurityGroup          `json:"securityGroup,omitempty"`
	SecurityGroupPolicySetStatus *v20170312.SecurityGroupPolicySet `json:"securityGroupPolicySet,omitempty"`
}

// +kubebuilder:object:root=true

// SecurityGroup is the Schema for the securitygroups API
type SecurityGroup struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   SecurityGroupSpec   `json:"spec,omitempty"`
	Status SecurityGroupStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SecurityGroupList contains a list of SecurityGroup
type SecurityGroupList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SecurityGroup `json:"items"`
}

func init() {
	SchemeBuilder.Register(&SecurityGroup{}, &SecurityGroupList{})
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityGroupSpec) DeepCopyInto(out *SecurityGroupSpec) {
	*out = *in
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.SecurityGroup != nil {
		in, out := &in.SecurityGroup, &out.SecurityGroup
		*out = new(v20170312.SecurityGroup)
		**out = **in
	}
	if in.SecurityGroupPolicySet != nil {
		in, out := &in.SecurityGroupPolicySet, &out.SecurityGroupPolicySet
		*out = new(v20170312.SecurityGroupPolicySet)
		**out = **in
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityGroupStatus) DeepCopyInto(out *SecurityGroupStatus) {
	*out = *in
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.Reason != nil {
		in, out := &in.Reason, &out.Reason
		*out = new(string)
		**out = **in
	}
	if in.Code != nil {
		in, out := &in.Code, &out.Code
		*out = new(string)
		**out = **in
	}
	if in.LastRetry != nil {
		in, out := &in.LastRetry, &out.LastRetry
		*out = new(string)
		**out = **in
	}
	if in.RetryCount != nil {
		in, out := &in.RetryCount, &out.RetryCount
		*out = new(int)
		**out = **in
	}
	if in.SecurityGroupStatus != nil {
		in, out := &in.SecurityGroupStatus, &out.SecurityGroupStatus
		*out = new(v20170312.SecurityGroup)
		**out = **in
	}
	if in.SecurityGroupPolicySetStatus != nil {
		in, out := &in.SecurityGroupPolicySetStatus, &out.SecurityGroupPolicySetStatus
		*out = new(v20170312.SecurityGroupPolicySet)
		**out = **in
	}
}
