---
name: Greetings

on: push

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: 'Thanks for your issue, we will look into thi issue '
          pr-message: Thanks for your pr, we will look into thi pr
  config-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8.10
      - run: python --version
      - uses: kubecooler/kube-cooler-tool-setup@v0.0.1
      - run: ./setup.sh
      - run: workflow/incremental-pre-commit.sh
